<?php
/**
 * Groups configuration for default Minify implementation
 * @package Minify
 *
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/_min/builder/
 **/

return array(
   'js1-3' => array(
     '//_assets/js/lib/jquery-ui-1.8.13.custom.js',
     '//_assets/js/lib/jquery.ass-array.js',
     '//_assets/js/lib/jquery.ba-hashchange.js',
     '//_assets/js/lib/jquery.rich-array.js',
     '//_assets/js/lib/jquery.rich-array2-extra.js',
     '//_assets/js/lib/jquery.timeago.js',
     '//_assets/js/lib/jquery.metadata.js',
     '//_assets/js/lib/jquery.mb.YTPlayer.js',
     '//_assets/js/lib/jquery-syntax/public/jquery.syntax.js',
     '//_assets/js/lib/jquery-syntax/public/jquery.syntax.cache.js',
     '//_assets/js/lib/innershiv.js',
     '//_assets/js/src/1.jquery.custom.functions.js',
     '//_assets/js/src/1.jquery.custom.selectors.js',
     '//_assets/js/src/2.jquery.custom.events.clickoutside.js',
     '//_assets/js/src/5.constants.js',
     '//_assets/js/src/6.settings.js',
     '//_assets/js/src/7.text.js',
     '//_assets/js/src/ajax.-.js',
     '//_assets/js/src/ajax.html.js',
     '//_assets/js/src/anagram.-.js',
//     '//_assets/js/src/anagram.chunk.js',
//     '//_assets/js/src/anagram.get.js',
//     '//_assets/js/src/anagram.letter.js',
//     '//_assets/js/src/anagram.total.js',
//     '//_assets/js/src/anagram.update.js',
     '//_assets/js/src/app.-.js',
     '//_assets/js/src/cache.-.js',
     '//_assets/js/src/pantography.-.js',
     '//_assets/js/src/comments.-.js',
     '//_assets/js/src/comments.scholia.js',
     '//_assets/js/src/cookie.js',
     '//_assets/js/src/editor.-.js',
     '//_assets/js/src/enface.-.js',
//     '//_assets/js/src/enface.blur.js',
//     '//_assets/js/src/enface.checktext.js',
//     '//_assets/js/src/enface.focus.js',
//     '//_assets/js/src/enface.goto.js',
//     '//_assets/js/src/enface.initialize.js',
//     '//_assets/js/src/enface.keyup.js',
//     '//_assets/js/src/enface.reset.js',
//     '//_assets/js/src/enface.source.js',
//     '//_assets/js/src/enface.target.js',
//     '//_assets/js/src/enface.wordscore.js',
     '//_assets/js/src/form.-.js',
     '//_assets/js/src/form.submit.js',
     '//_assets/js/src/form.validate.js',
     '//_assets/js/src/highlighter.-.js',
     '//_assets/js/src/nav.-.js',
     '//_assets/js/src/nav.arrows.js',
     '//_assets/js/src/nav.crumb.js',
     '//_assets/js/src/nav.fetch.js',
     '//_assets/js/src/nav.goto.js',
     '//_assets/js/src/nav.hash.js',
     '//_assets/js/src/nav.links.js',
     '//_assets/js/src/nav.refresh.js',
     '//_assets/js/src/nav.slider.js',
     '//_assets/js/src/nav.track.js',
     '//_assets/js/src/number.-.js',
     '//_assets/js/src/number.commas.js',
     '//_assets/js/src/number.range.js',
     '//_assets/js/src/string.-.js',
     '//_assets/js/src/string.diff.js',
     '//_assets/js/src/string.increment.js',
     '//_assets/js/src/string.levenshtein.js',
     '//_assets/js/src/string.strip.js',
     '//_assets/js/src/string.truncate.js',
     '//_assets/js/src/string.uncomma.js',
     '//_assets/js/src/tools.-.js',
     '//_assets/js/src/tools.blackletter.js',
     '//_assets/js/src/tools.code.js',
     '//_assets/js/src/tools.colorize.js',
     '//_assets/js/src/tools.diff.js',
     '//_assets/js/src/tools.help.js',
     '//_assets/js/src/tools.interlinear.js',
     '//_assets/js/src/ui.-.js',
     '//_assets/js/src/ui.addthis.js',
     '//_assets/js/src/ui.caret.js',
     '//_assets/js/src/ui.comments.js',
     '//_assets/js/src/ui.debug.js',
     '//_assets/js/src/ui.downloads.js',
     '//_assets/js/src/ui.draggables.js',
     '//_assets/js/src/ui.error.js',
     '//_assets/js/src/ui.escape.js',
     '//_assets/js/src/ui.focus.js',
     '//_assets/js/src/ui.height.js',
     '//_assets/js/src/ui.iframe.js',
     '//_assets/js/src/ui.image.js',
     '//_assets/js/src/ui.kill.js',
     '//_assets/js/src/ui.palette.js',
     '//_assets/js/src/ui.panels.js',
     '//_assets/js/src/ui.pinnables.js',
     '//_assets/js/src/ui.screencover.js',
     '//_assets/js/src/ui.stripes.js',
     '//_assets/js/src/ui.timeago.js',
     '//_assets/js/src/ui.video.js',
     '//_assets/js/src/url.-.js',
     '//_assets/js/src/user.-.js',
     '//_assets/js/src/user.clear.js',
     '//_assets/js/src/user.facebook.js',
     '//_assets/js/src/user.me.js',
     '//_assets/js/src/user.page.js',
     '//_assets/js/src/user.password.js',
     '//_assets/js/src/user.pending.js',
     '//_assets/js/src/user.popup.js',
     '//_assets/js/src/user.resend.js',
     '//_assets/js/src/user.signedin.js',
     '//_assets/js/src/user.signin.js',
     '//_assets/js/src/user.signout.js',
     '//_assets/js/src/user.signup.js',
     '//_assets/js/src/user.twitter.js',
     '//_assets/js/src/utils.-.js',
     '//_assets/js/src/versions.-.js',
     '//_assets/js/src/zz.run.js'
   ),
   'css1-1' => array(
     '//_assets/css/lib/1.style-reset-html5-boilerplate.css',
     '//_assets/css/lib/2.960_12_col.css',
     '//_assets/css/src/1.site.css',
     '//_assets/css/src/3.colors.css',
     '//_assets/css/src/3.fonts.css',
     '//_assets/css/src/3.headers.css',
     '//_assets/css/src/3.images.css',
     '//_assets/css/src/3.sprite.css',
     '//_assets/css/src/5.pantography.css',
     '//_assets/css/src/5.code.css',
     '//_assets/css/src/5.colophon.css',
     '//_assets/css/src/5.enface.css',
     '//_assets/css/src/5.enface.interlinear.css',
     '//_assets/css/src/5.tables-graphs.css',
     '//_assets/css/src/5.help.css',
     '//_assets/css/src/5.footer.css',
     '//_assets/css/src/5.help.css',
     '//_assets/css/src/5.home.css',
     '//_assets/css/src/5.nav.css',
     '//_assets/css/src/5.notes.css',
     '//_assets/css/src/5.palette.css',
     '//_assets/css/src/5.promos.css',
     '//_assets/css/src/5.rss.css',
     '//_assets/css/src/5.scholia.css',
     '//_assets/css/src/5.share.css',
     '//_assets/css/src/5.signupin.css',
     '//_assets/css/src/5.sitemap.css',
     '//_assets/css/src/5.tags.css',
     '//_assets/css/src/7.theme.css',
     '//_assets/css/lib/9.style-helpers-html5-boilerplate.css',
     '//_assets/css/lib/9.style-print-html5-boilerplate.css',
     '//_assets/css/lib/addthis-widget60-customised.css',
     '//_assets/css/lib/addthis-counter60-customised.css',
     '//_assets/css/lib/mb.YTVPlayer.css',
     '//_assets/css/src/8.handheld.css',
     '//_assets/css/src/8.handheld-landscape.css',
     '//_assets/css/src/8.handheld-portrait.css',
     '//_assets/css/src/9.print.css'
   ),
   'js-tablescharts' => array(
     '//_assets/js/lib/jquery.dataTables.js',
     '//_assets/js/lib/highcharts.js',
     '//_assets/js/src/ui.charts.js'
   )

);
