<?php
/**
 * Groups configuration for default Minify implementation
 * @package Minify
 *
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/_min/builder/
 **/

return array(
     'js1-2' => array(
//   '//_etc/javascript/lib/jquery-1.4.2.js',
   '//_etc/javascript/lib/jquery.ass-array.js',
   '//_etc/javascript/lib/jquery.ba-hashchange.js',
   '//_etc/javascript/lib/jquery.rich-array.js',
   '//_etc/javascript/lib/jquery.rich-array2-extra.js',
   '//_etc/javascript/lib/jquery.timeago.js',
   '//_etc/libraries/jquery-syntax/public/jquery.syntax.js',
   '//_etc/libraries/jquery-syntax/public/jquery.syntax.cache.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shCore.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shAutoloader.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shBrushDiff.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shBrushPerl.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shBrushPhp.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shBrushSql.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shBrushJScript.js',
//   '//_etc/libraries/syntaxhighlighter/scripts/shBrushXml.js',
//   '//_etc/libraries/google-code-prettify/src/prettify.js',
//   '//_etc/libraries/google-code-prettify/src/lang-css.js',
//   '//_etc/libraries/google-code-prettify/src/lang-sql.js',
//   '//_etc/javascript/lib/jquery.syntaxhighlighter.js',
//   '//_etc/javascript/lib/evernote-noteit.js',
//   '//_etc/javascript/lib/facebook-all.js',
//   '//_etc/javascript/lib/jquery.ui.1.8.2.js',
//   '//_etc/javascript/lib/nicEdit.js',
   '//_etc/javascript/src/00.jquery.custom.selectors.js',
   '//_etc/javascript/src/01.jquery.custom.events.clickoutside.js',
   '//_etc/javascript/src/10.constants.js',
   '//_etc/javascript/src/20.settings.js',
   '//_etc/javascript/src/30.text.js',
   '//_etc/javascript/src/ajax.--------------.js',
   '//_etc/javascript/src/ajax.html.js',
   '//_etc/javascript/src/anagram.----------.js',
   '//_etc/javascript/src/anagram.chunk.js',
   '//_etc/javascript/src/anagram.get.js',
   '//_etc/javascript/src/anagram.letter.js',
   '//_etc/javascript/src/anagram.total.js',
   '//_etc/javascript/src/anagram.update.js',
   '//_etc/javascript/src/app.--------------.js',
   '//_etc/javascript/src/cache.------------.js',
   '//_etc/javascript/src/comments.-------.js',
   '//_etc/javascript/src/comments.scholia.js',
   '//_etc/javascript/src/cookie.js',
   '//_etc/javascript/src/editor.-------------.js',
   '//_etc/javascript/src/enface.------------.js',
   '//_etc/javascript/src/enface.blur.js',
   '//_etc/javascript/src/enface.checktext.js',
   '//_etc/javascript/src/enface.focus.js',
   '//_etc/javascript/src/enface.initialize.js',
   '//_etc/javascript/src/enface.keyup.js',
   '//_etc/javascript/src/enface.reset.js',
   '//_etc/javascript/src/enface.source.js',
   '//_etc/javascript/src/enface.target.js',
   '//_etc/javascript/src/enface.wordscore.js',
   '//_etc/javascript/src/form.--------------.js',
   '//_etc/javascript/src/form.submit.js',
   '//_etc/javascript/src/form.validate.js',
   '//_etc/javascript/src/highlighter.-------.js',
   '//_etc/javascript/src/nav.---------------.js',
   '//_etc/javascript/src/nav.arrows.js',
   '//_etc/javascript/src/nav.crumb.js',
   '//_etc/javascript/src/nav.fetch.js',
   '//_etc/javascript/src/nav.goto.js',
   '//_etc/javascript/src/nav.hash.js',
   '//_etc/javascript/src/nav.links.js',
   '//_etc/javascript/src/nav.prefetch.js',
   '//_etc/javascript/src/nav.refresh.js',
   '//_etc/javascript/src/nav.slider.js',
   '//_etc/javascript/src/nav.track.js',
   '//_etc/javascript/src/number.-----------.js',
   '//_etc/javascript/src/number.commas.js',
   '//_etc/javascript/src/number.range.js',
   '//_etc/javascript/src/string.--------------.js',
   '//_etc/javascript/src/string.diff.js',
   '//_etc/javascript/src/string.increment.js',
   '//_etc/javascript/src/string.levenshtein.js',
   '//_etc/javascript/src/string.strip.js',
   '//_etc/javascript/src/string.truncate.js',
   '//_etc/javascript/src/string.uncomma.js',
   '//_etc/javascript/src/tools.---------------.js',
   '//_etc/javascript/src/tools.blackletter.js',
   '//_etc/javascript/src/tools.colorize.js',
   '//_etc/javascript/src/tools.diff.js',
   '//_etc/javascript/src/tools.help.js',
   '//_etc/javascript/src/tools.interlinear.js',
   '//_etc/javascript/src/tools.code.js',
   '//_etc/javascript/src/ui.------------------.js',
   '//_etc/javascript/src/ui.caret.js',
   '//_etc/javascript/src/ui.clip.js',
   '//_etc/javascript/src/ui.comments.js',
   '//_etc/javascript/src/ui.debug.js',
   '//_etc/javascript/src/ui.downloads.js',
   '//_etc/javascript/src/ui.draggables.js',
   '//_etc/javascript/src/ui.error.js',
   '//_etc/javascript/src/ui.escape.js',
   '//_etc/javascript/src/ui.focus.js',
   '//_etc/javascript/src/ui.height.js',
   '//_etc/javascript/src/ui.kill.js',
   '//_etc/javascript/src/ui.image.js',
   '//_etc/javascript/src/ui.panels.js',
   '//_etc/javascript/src/ui.palette.js',
   '//_etc/javascript/src/ui.pinnables.js',
   '//_etc/javascript/src/ui.screencover.js',
   '//_etc/javascript/src/ui.stripes.js',
   '//_etc/javascript/src/ui.timeago.js',
   '//_etc/javascript/src/ui.versions.js',
   '//_etc/javascript/src/url.----------------.js',
   '//_etc/javascript/src/user.--------------.js',
   '//_etc/javascript/src/user.clear.js',
   '//_etc/javascript/src/user.facebook.js',
   '//_etc/javascript/src/user.twitter.js',
   '//_etc/javascript/src/user.me.js',
   '//_etc/javascript/src/user.page.js',
   '//_etc/javascript/src/user.password.js',
   '//_etc/javascript/src/user.pending.js',
   '//_etc/javascript/src/user.popup.js',
   '//_etc/javascript/src/user.resend.js',
   '//_etc/javascript/src/user.signedin.js',
   '//_etc/javascript/src/user.signin.js',
   '//_etc/javascript/src/user.signout.js',
   '//_etc/javascript/src/user.signup.js',
   '//_etc/javascript/src/utils.---------------.js',
   '//_etc/javascript/src/versions.----------.js'
   ),
     'css1-1' => array(
   '//_etc/css/lib/1.style-reset-html5-boilerplate.css',
   '//_etc/css/lib/2.960.css',
   '//_etc/css/src/1.site.css',
   '//_etc/css/src/5.code.css',
   '//_etc/css/src/5.enface.css',
   '//_etc/css/src/5.fonts.css',
   '//_etc/css/src/5.home.css',
   '//_etc/css/src/5.images.css',
   '//_etc/css/src/5.nav.css',
   '//_etc/css/src/5.notes.css',
   '//_etc/css/src/5.palette.css',
   '//_etc/css/src/5.promos.css',
   '//_etc/css/src/5.signupin.css',
   '//_etc/css/src/5.sitemap.css',
   '//_etc/css/src/5.sprite.css',
   '//_etc/css/src/5.tags.css',
   '//_etc/css/src/7.theme.css',
   '//_etc/css/lib/9.style-helpers-html5-boilerplate.css',
   '//_etc/css/lib/9.style-print-html5-boilerplate.css',
   '//_etc/css/src/8.handheld-landscape.css',
   '//_etc/css/src/8.handheld-portrait.css',
   '//_etc/css/src/9.print.css'
   ),
   'cssprint1-1' => array('//_etc/css/Print.css'),
   'cssie6fixes1-1' => array('//_etc/css/IE6.css'),
   'cssie7fixes1-1' => array('//_etc/css/IE7.css')
);
