<?php
/**
 * Groups configuration for default Minify implementation
 * @package Minify
 *
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/_min/builder/
 **/

return array(
     'js1-2' => array(
//   '../_javascript/lib/jquery-1.4.2.js',
   '../_javascript/lib/jquery.ass-array.js',
   '../_javascript/lib/jquery.ba-hashchange.js',
   '../_javascript/lib/jquery.rich-array.js',
   '../_javascript/lib/jquery.rich-array2-extra.js',
   '../_javascript/lib/jquery.timeago.js',
//   '../_javascript/lib/evernote-noteit.js',
//   '../_javascript/lib/facebook-all.js',
//   '../_javascript/lib/jquery.ui.1.8.2.js',
//   '../_javascript/lib/nicEdit.js',
   '../_javascript/src/00.jquery.custom.selectors.js',
   '../_javascript/src/01.jquery.custom.events.clickoutside.js',
   '../_javascript/src/10.constants.js',
   '../_javascript/src/20.settings.js',
   '../_javascript/src/30.text.js',
   '../_javascript/src/ajax.--------------.js',
   '../_javascript/src/ajax.html.js',
   '../_javascript/src/anagram.----------.js',
   '../_javascript/src/anagram.chunk.js',
   '../_javascript/src/anagram.get.js',
   '../_javascript/src/anagram.letter.js',
   '../_javascript/src/anagram.total.js',
   '../_javascript/src/anagram.update.js',
   '../_javascript/src/app.--------------.js',
   '../_javascript/src/cache.------------.js',
   '../_javascript/src/comments.-------.js',
   '../_javascript/src/comments.scholia.js',
   '../_javascript/src/cookie.js',
   '../_javascript/src/editor.-------------.js',
   '../_javascript/src/enface.------------.js',
   '../_javascript/src/enface.blur.js',
   '../_javascript/src/enface.checktext.js',
   '../_javascript/src/enface.focus.js',
   '../_javascript/src/enface.initialize.js',
   '../_javascript/src/enface.keyup.js',
   '../_javascript/src/enface.reset.js',
   '../_javascript/src/enface.source.js',
   '../_javascript/src/enface.target.js',
   '../_javascript/src/enface.wordscore.js',
   '../_javascript/src/form.--------------.js',
   '../_javascript/src/form.submit.js',
   '../_javascript/src/form.validate.js',
   '../_javascript/src/nav.---------------.js',
   '../_javascript/src/nav.arrows.js',
   '../_javascript/src/nav.crumb.js',
   '../_javascript/src/nav.fetch.js',
   '../_javascript/src/nav.goto.js',
   '../_javascript/src/nav.hash.js',
   '../_javascript/src/nav.links.js',
   '../_javascript/src/nav.prefetch.js',
   '../_javascript/src/nav.refresh.js',
   '../_javascript/src/nav.slider.js',
   '../_javascript/src/nav.track.js',
   '../_javascript/src/number.-----------.js',
   '../_javascript/src/number.commas.js',
   '../_javascript/src/number.range.js',
   '../_javascript/src/string.--------------.js',
   '../_javascript/src/string.diff.js',
   '../_javascript/src/string.increment.js',
   '../_javascript/src/string.levenshtein.js',
   '../_javascript/src/string.strip.js',
   '../_javascript/src/string.truncate.js',
   '../_javascript/src/string.uncomma.js',
   '../_javascript/src/tools.---------------.js',
   '../_javascript/src/tools.blackletter.js',
   '../_javascript/src/tools.colorize.js',
   '../_javascript/src/tools.diff.js',
   '../_javascript/src/tools.help.js',
   '../_javascript/src/tools.interlinear.js',
   '../_javascript/src/ui.------------------.js',
   '../_javascript/src/ui.caret.js',
   '../_javascript/src/ui.clip.js',
   '../_javascript/src/ui.comments.js',
   '../_javascript/src/ui.debug.js',
   '../_javascript/src/ui.downloads.js',
   '../_javascript/src/ui.draggables.js',
   '../_javascript/src/ui.error.js',
   '../_javascript/src/ui.escape.js',
   '../_javascript/src/ui.focus.js',
   '../_javascript/src/ui.height.js',
   '../_javascript/src/ui.kill.js',
   '../_javascript/src/ui.image.js',
   '../_javascript/src/ui.panels.js',
   '../_javascript/src/ui.pinnables.js',
   '../_javascript/src/ui.screencover.js',
   '../_javascript/src/ui.stripes.js',
   '../_javascript/src/ui.timeago.js',
   '../_javascript/src/ui.versions.js',
   '../_javascript/src/url.----------------.js',
   '../_javascript/src/user.--------------.js',
   '../_javascript/src/user.clear.js',
   '../_javascript/src/user.facebook.js',
   '../_javascript/src/user.twitter.js',
   '../_javascript/src/user.me.js',
   '../_javascript/src/user.page.js',
   '../_javascript/src/user.password.js',
   '../_javascript/src/user.pending.js',
   '../_javascript/src/user.popup.js',
   '../_javascript/src/user.resend.js',
   '../_javascript/src/user.signedin.js',
   '../_javascript/src/user.signin.js',
   '../_javascript/src/user.signout.js',
   '../_javascript/src/user.signup.js',
   '../_javascript/src/utils.---------------.js',
   '../_javascript/src/versions.----------.js'
   ),
     'css1-1' => array(
   '../_css/lib/960.css',
   '../_css/lib/reset.css',
   '../_css/lib/text.css',
   '../_css/src/0_sprite.css',
   '../_css/src/1_site.css',
   '../_css/src/2_nav.css',
//   '../_css/src/Debug.css',
   '../_css/src/promos.css',
   '../_css/src/signupin.css',
   '../_css/src/sitemap.css',
   '../_css/src/themes.css',
   '../_css/src/z1_notes.css',
   '../_css/src/z2_tags.css',
   '../_css/src/z3_home.css',
   '../_css/src/z5_enface.css',
   '../_css/src/z9_fonts.css'
     ),
     'cssprint1-1' => array('../_css/nb_print.css'),
     'cssie6fixes1-1' => array('../_css/nb_ie6.css'),
     'cssie7fixes1-1' => array('../_css/nb_ie7.css')
);
